sources:
    osm:
        type: TopoJSON
        url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=vector-tiles-JUsa0Gc

cameras:
    cam:
        type: perspective
        vanishing_point: [0, -500]

lights:
    dir:
        type: directional
        direction: [.1, .5, -1]
        diffuse: .7
        ambient: .5

layers:
    water:
        data: { source: osm }
        draw:
            polygons:
                order: function () { return feature.sort_key; }
                color: '#353535'
    earth:
        data: { source: osm }
        draw:
            polygons:
                order: function () { return feature.sort_key; }
                color: '#555'
    landuse:
        data: { source: osm }
        draw:
            polygons:
                order: function () { return feature.sort_key; }
                color: '#666'
    roads:
        data: { source: osm }
        filter: { not: { kind: ferry } }
        draw:
            lines:
                order: function () { return feature.sort_key; }
                color: '#777'
                width: 5
        labels:
            filter: { name: true }
            draw:
                text:
                    font:
                        family: Helvetica
                        fill: white
                        size: 11px
    buildings:
        data: { source: osm }
        draw:
            polygons:
                style: buildings
                order: function () { return feature.sort_key; }
                color: '#999'
                extrude: true
styles:
    buildings:
        base: polygons
        shaders:
            blocks:
                color: |
                    color.rgb *= vec3(min((worldPosition().z*.001 + .5),1.));